version: '3.6'

services:
  plugin-repository-api:
    build:
      context: LacmusPluginsRepository
      dockerfile: Dockerfile
    container_name: plugin-repository
    volumes:
      - ./plugins:/app/plugins
    networks:
      - proxynet
networks:
  proxynet:
    name: proxynet